Task/6 login page
Team-SE-CED/search-engine pull request #21
Opened 2024-09-21 07:31 UTC by whiteNsky

#6

### UPDATE V1.0.1
Changes:
- [x] Added togglePassword
- [x] Fixed eye-icon image positioning
- [x] Changed the font style of login-forms
- [x] Resized header to 1.5px;

### Problem
- Makita ang eye-icon maskig wala pa ni type ang user og password

### Solution

- [x] Added v-if="password.length > 0" to hide the eye-icon

2024-09-22 07:35 UTC, Techies-John commented on components/LoginPage.vue
> +<script>
use <script setup lang="ts">, try researching more about vue compositions api

2024-09-22 07:39 UTC, Techies-John commented on components/LoginPage.vue
> +                <img :src="showPassword ? '/assets/static-images/eye-open.png' : '/assets/static-images/eye-close.png'" id="eyeicon" />
use computed()

2024-09-22 15:35 UTC, sggenDebugs submitted a review, later dismissed
Okay looks good. 👍🏿🖤

2024-09-22 22:25 UTC, Techies-John requested changes

2024-09-22 22:25 UTC, Techies-John commented on components/LoginPage.vue
> +              <input :type="showPassword ? 'text' : 'password'" id="password" v-model="password" class="form-control"
No logics in template. Use computed.

2024-09-22 22:25 UTC, Techies-John commented on components/LoginPage.vue
> +                <img :src="showPassword ? eyeOpen : eyeClose" id="eyeicon" />
Use computed

2024-09-22 22:25 UTC, Techies-John commented on components/LoginPage.vue
> +                :style="{ width: passwordStrengthPercentage + '%' }"></div>
use computed for :class and :style

2024-09-24 13:54 UTC, Techies-John approved these changes

2024-09-24 14:30 UTC, sggenDebugs approved these changes
okay looks nice 👍🏿👍🏿🖤🖤

2024-09-24 14:49 UTC, merged