Welcome page
Team-SE-CED/search-engine pull request #27
Opened 2024-09-27 13:56 UTC by whiteNsky

#Welcome Page

### UPDATE V1.0.0

- [x] Added clickable cursor
- [x] Linked the welcome page to login page

2024-09-27 18:53 UTC, Techies-John commented
Tarunga ang PR and commit message PJ sunda ang correct format

2024-09-27 18:53 UTC, Techies-John commented
Tabangi kog butang og tango sa atong balaod para ma organize ta tanan

2024-09-27 19:06 UTC, Techies-John requested changes
Overall chada kaayo syag design but,

- Avoid having two words in pages as much as possible. If "homepage" then "home" ra, if "aboutpage" then "about" ra.

- Also, try separate components by adding folders base on pages.

2024-09-27 19:06 UTC, Techies-John commented on components/WelcomePage.vue
Sunda ni nga file directory and naming: 
components->Welcome->Page.vue

2024-09-28 14:47 UTC, Techies-John approved these changes

2024-09-30 01:46 UTC, sggenDebugs approved these changes

2024-09-30 02:24 UTC, merged