Task/32 user can select search results
Team-SE-CED/search-engine pull request #47
Opened 2024-10-02 19:29 UTC by Techies-John

## Problem/Issue:
- #32 

1. Users cannot click on the suggested results.
2. Users cannot navigate to the search results page when they press `Enter`.
3. The components are disorganized.

## Proposed Solution:
1. Implement functionality that redirects users to a specific paper by accessing its `id`.
2. Ensure that when users press `Enter`, only the suggestions provided by the search engine are displayed.
3. Restructure and rename components.

**Note: As I progressed, I encountered several bugs and I've created separate tasks to address them.**

2024-10-02 23:58 UTC, nonsensenv submitted a review, later dismissed

2024-10-03 14:47 UTC, nonsensenv submitted a review, later dismissed

2024-10-05 03:23 UTC, sggenDebugs requested changes
we'll talk about the db, services, use-case soon if we both agree on it or not before i approve this.

2024-10-06 09:06 UTC, Techies-John commented on components/Welcome/Page.vue
> +
Okay I'll remove it

2024-10-06 09:06 UTC, Techies-John commented on components/login/Page.vue
> +html {
Okay I'll remove it

2024-10-06 09:06 UTC, Techies-John commented on components/login/Page.vue
> +html {
Okay I'll remove it

2024-10-07 00:09 UTC, sggenDebugs approved these changes
approved ching chong

2024-10-07 00:10 UTC, nonsensenv approved these changes
next time please put version (e.g  alpha build v1.0.5)

2024-10-07 00:12 UTC, sggenDebugs commented
Picture is not display correctly. Take note thanks ching chong

2024-10-07 00:31 UTC, closed without merging

2024-10-07 03:36 UTC, Techies-John commented
> next time please put version (e.g  alpha build v1.0.5)

Response (Version 1.0.0)
- Okay brad