fix: fix navigate to signup
Team-SE-CED/search-engine pull request #91
Opened 2024-12-14 11:47 UTC by sggenDebugs

### Problem: 

- Login page does not go to signup page after clicking "Sign Up".
- Sign Up Function is absent in the code

### Solution:

- add href value of signup
- redo the code of the signup function

2024-12-14 14:19 UTC, nonsensenv approved these changes

2024-12-16 05:39 UTC, Techies-John approved these changes

2024-12-16 07:24 UTC, Techies-John requested changes
I have made some small fixes on the Main branch. Please pull the changes first before I approve.

2024-12-16 07:32 UTC, nonsensenv approved these changes

2024-12-19 05:58 UTC, merged